/* tslint:disable */
/* eslint-disable */
/**
 * Miigo.Admin
 * 前后端分离架构(.NET8/Vue3)<br/>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { StatusEnum } from './status-enum';
import { SysFile } from './sys-file';
 /**
 * SiteMstr输出参数
 *
 * @export
 * @interface SiteMstrOutput
 */
export interface SiteMstrOutput {

    /**
     * Id
     *
     * @type {number}
     * @memberof SiteMstrOutput
     */
    id?: number;

    /**
     * 名称
     *
     * @type {string}
     * @memberof SiteMstrOutput
     */
    name?: string | null;

    /**
     * 图标
     *
     * @type {string}
     * @memberof SiteMstrOutput
     */
    logo?: string | null;

    /**
     * @type {SysFile}
     * @memberof SiteMstrOutput
     */
    logoAttachment?: SysFile;

    /**
     * 描述
     *
     * @type {string}
     * @memberof SiteMstrOutput
     */
    desc?: string | null;

    /**
     * @type {StatusEnum}
     * @memberof SiteMstrOutput
     */
    status?: StatusEnum;

    /**
     * 过期时间
     *
     * @type {Date}
     * @memberof SiteMstrOutput
     */
    expiredTime?: Date | null;

    /**
     * Url地址
     *
     * @type {string}
     * @memberof SiteMstrOutput
     */
    url?: string | null;

    /**
     * 创建者姓名
     *
     * @type {string}
     * @memberof SiteMstrOutput
     */
    createUserName?: string | null;

    /**
     * 修改者姓名
     *
     * @type {string}
     * @memberof SiteMstrOutput
     */
    updateUserName?: string | null;
}
