/* tslint:disable */
/* eslint-disable */
/**
 * Miigo.Admin
 * 前后端分离架构(.NET8/Vue3)<br/>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { StatusEnum } from './status-enum';
 /**
 * SiteMstr分页查询输入参数
 *
 * @export
 * @interface SiteMstrInput
 */
export interface SiteMstrInput {

    /**
     * 当前页码
     *
     * @type {number}
     * @memberof SiteMstrInput
     */
    page?: number;

    /**
     * 页码容量
     *
     * @type {number}
     * @memberof SiteMstrInput
     */
    pageSize?: number;

    /**
     * 排序字段
     *
     * @type {string}
     * @memberof SiteMstrInput
     */
    field?: string | null;

    /**
     * 排序方向
     *
     * @type {string}
     * @memberof SiteMstrInput
     */
    order?: string | null;

    /**
     * 降序排序
     *
     * @type {string}
     * @memberof SiteMstrInput
     */
    descStr?: string | null;

    /**
     * 关键字查询
     *
     * @type {string}
     * @memberof SiteMstrInput
     */
    searchKey?: string | null;

    /**
     * Id
     *
     * @type {number}
     * @memberof SiteMstrInput
     */
    id?: number | null;

    /**
     * 名称
     *
     * @type {string}
     * @memberof SiteMstrInput
     */
    name?: string | null;

    /**
     * 描述
     *
     * @type {string}
     * @memberof SiteMstrInput
     */
    desc?: string | null;

    /**
     * @type {StatusEnum}
     * @memberof SiteMstrInput
     */
    status?: StatusEnum;
}
